feature/should-fall-through
jfairbank/redux-saga-router pull request #11
Opened 2017-04-01 13:32 UTC by TeoTN

Implement #10 - optional fall through pattern matching

2017-04-26 14:32 UTC, jfairbank requested changes

2017-04-26 14:32 UTC, jfairbank commented on README.md
> +  shouldFallThrough: true,
matchAll

2017-04-26 14:32 UTC, jfairbank commented on README.md
> +`shouldFallThrough` | Determines whether route matching should take into account all matching rules
matchAll

2017-04-26 14:34 UTC, jfairbank commented
Hi, @TeoTN. I commented on two fixes in the docs.

Also, can you bring this PR current with master and fix any merge conflicts. I appreciate that you put all the changes in #13, but I'd prefer to have separate PRs. If you can fix this PR, then I'm ready to merge :)

2017-04-28 17:20 UTC, TeoTN commented
I have updated `README.md` and merged with master - I hope that it suits you and will be released soon :) Thanks for your help!

2017-05-02 20:32 UTC, jfairbank approved these changes

2017-05-02 20:32 UTC, merged

2017-05-02 20:33 UTC, jfairbank commented
Thanks, @TeoTN!

I'll try to get a release out in a day or two.